default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database:  <%= ENV.fetch("NANOEVENT_DB") { "db/development.sqlite3" } %>
  adapter: <%= ENV.fetch("NANOEVENT_ADAPTER_DB") { "sqlite3" } %>
  host: <%= ENV.fetch("NANOEVENT_HOST_DB") { "" } %>
  username: <%= ENV.fetch("NANOEVENT_USER_DB") { "" } %>
  password: <%= ENV.fetch("NANOEVENT_PASSWORD_DB") { "" } %>
  port: <%= ENV.fetch("NANOEVENT_PORT_DB") { "" } %>

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3